resolver: lts-19.24

packages:
  - .

extra-deps:
  - co-log-core-0.3.1.0
  - postgresql-error-codes-1.0.1
  - tomland-1.3.3.1
  - validation-selective-0.1.0.1
  - openai-hs-0.3.0.0
  - openai-servant-0.3.0.0@sha256:bb061100554ca97e2d26765d0ec57d76126342ca49e537483282f36b6e92b082,1605
  - git: https://github.com/haskell-servant/servant
    commit: d05da71f09be08131d29a2c17f613a4bd71faea2
    subdirs:
      - servant-auth/servant-auth-server

allow-newer: true
